// ===============================
// Plugin 管理
// ===============================
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

// ===============================
// 依赖仓库管理
// ===============================
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        google()
        // TVBox 本地 aar / so
        flatDir { dirs "$rootDir/app/libs" }
        maven { url "https://jitpack.io" }
        maven {
            url "http://4thline.org/m2"
            allowInsecureProtocol = true
        }
    }
}

// ===============================
// 引入 media 源码（关键）
// media 与 tv 必须是同级目录
// ===============================
apply from: file("../media/core_settings.gradle")

// ===============================
// TVBox 原有模块
// ===============================
include ':app'
include ':catvod'
include ':chaquo'
include ':quickjs'

// ===============================
rootProject.name = "TV"
