pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        google()
        flatDir { dirs "$rootDir/app/libs" }
        maven { url "https://jitpack.io" }
        maven {
            url "http://4thline.org/m2"
            allowInsecureProtocol = true
        }
    }
}

/**
 * ===== AndroidX Media3 源码引入（关键）=====
 */

// media3 模块名前缀（必须）
gradle.ext.androidxMediaModulePrefix = "media3-"

// 引入 media 源码工程
// ⚠️ 要求 media 和 tv 是同级目录
apply from: file("../media/core_settings.gradle")

/**
 * ===== TVBox 原有模块 =====
 */
include ':app'
include ':catvod'
include ':chaquo'
include ':quickjs'

rootProject.name = "TV"
